#!/bin/sh

install -m0664 -o root -g utmp /dev/null /run/utmp

[ ! -e /var/log/wtmp ]		&& install -m0664 -o root -g utmp /dev/null /var/log/wtmp
[ ! -e /var/log/btmp ]		&& install -m0600 -o root -g utmp /dev/null /var/log/btmp
[ ! -e /var/log/lastlog ]	&& install -m0600 -o root -g utmp /dev/null /var/log/lastlog

install -dm1777 /tmp/.X11-unix /tmp/.ICE-unix
rm -f /etc/nologin /forcefsck /forcequotacheck /fastboot
